### ISSUE TITLE
Twitter link is dead

### ISSUE THREAD

**Issue by textpain** [Rajdave69/my-website-2#1]
Hi Raj, love your [website](https://rajtech.me/me/).

There is some kind of problem with a Twitter link though — instead of opening Twitter, it just refreshes the page.

**Comment by Rajdave69** [comment]
Thank you!

I am aware of this issue, it is because my twitter account was wrongfully suspended and twitter hasn't replied yet. I probably should disable the link all together since I doubt I'll be getting the account back. Thanks for creating an issue though
